import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const session = useSession();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Logged in with {session.data?.user?.name}</div>
      <div>
        {session && (
          <img src={session.data?.user?.image!} width={60} height={60} />
        )}
      </div>
      <button onClick={() => signIn()}>Sign In!</button>
      <button onClick={() => signOut()}>Sign out!</button>
    </div>
  );
};

export default Home;
