import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const session = useSession();
  return (
    <div className="container mx-auto bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <button onClick={() => signIn()}>Sign In!</button>
      <button onClick={() => signOut()}>Sign out!</button>
      <button
        onClick={() =>
          fetch(`api/tweets?id=1495475945121193995`, { method: "DELETE" })
        }
      >
        DELETE TWEET
      </button>
    </div>
  );
};

export default Home;
